name: budgetly
description: "A zero-budgetting based app."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  get_it: ^7.6.7
  freezed_annotation: ^2.4.1
  flutter_bloc: ^8.1.4
  injectable: ^2.3.5
  dartz: ^0.10.1
  dropdown_button2: ^2.3.9
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.8
  freezed: ^2.4.7
  injectable_generator: ^2.5.1

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/icons/
    - assets/images/vectors/
    - assets/images/countries_flags/

  fonts:
    - family: Syntha
      fonts:
        - asset: assets/fonts/Syntha.ttf
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat.ttf
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-ExtraBold.ttf
          weight: 800
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf

